sudo: required
services: 
  - docker

dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic

before_install:
  - docker build -t kukaisir/kinect-vision-no-gpu kinect_vision_no_gpu/
